# Generated by Django 5.1.3 on 2024-11-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
